name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: mgna7
        password: ${{ secrets.CI_CD_PAT }}

    - name: Build the hello-world Docker image
      run: |
        docker pull mhart/alpine-node
        docker image tag mhart/alpine-node ghcr.io/mgna7/alpine-mycovid:latest
        docker image push ghcr.io/mgna7/alpine-mycovid:latest
